"""Shared matching and display metadata. Distances operate on these features only."""

FEATURE_GROUPS = {
    "physical": {
        "features": ["height_inches", "weight"],
        "default_weight": 0.5,
        "description": "Height and weight",
        "label": "Physical",
        "short": "PHY",
        "group": "Physical",
        "desc": "Height, weight",
    },
    "scoring_volume": {
        "features": ["PTS", "FGA", "FG3A", "FTA", "MIN", "pts_share", "fga_share", "min_share"],
        "default_weight": 1.0,
        "description": "Points, shots, minutes",
        "label": "Scoring Volume",
        "short": "SCR VOL",
        "group": "Scoring",
        "desc": "PTS, FGA, FTA, MIN",
    },
    "scoring_efficiency": {
        "features": ["ts_pct", "efg_pct", "fg_pct", "fg3_pct", "ft_pct"],
        "default_weight": 1.0,
        "description": "Shooting percentages",
        "label": "Efficiency",
        "short": "EFF",
        "group": "Scoring",
        "desc": "TS%, eFG%, FG%",
    },
    "shot_profile": {
        "features": [
            "pct_fga_restricted",
            "pct_fga_paint",
            "pct_fga_midrange",
            "pct_fga_corner3",
            "pct_fga_above_break3",
        ],
        "default_weight": 1.0,
        "description": "Where they shoot from",
        "label": "Shot Profile",
        "short": "SHT PRO",
        "group": "Shooting",
        "desc": "Rim, Paint, Mid, 3PT",
    },
    "shot_creation": {
        "features": [
            "PCT_UAST_2PM",
            "PCT_UAST_3PM",
            "PCT_UAST_FGM",
            "PULL_UP_FGA",
            "PULL_UP_FG_PCT",
            "PULL_UP_FG3_PCT",
            "CATCH_SHOOT_FGA",
            "CATCH_SHOOT_FG_PCT",
            "CATCH_SHOOT_FG3_PCT",
        ],
        "default_weight": 1.0,
        "description": "Self-created vs assisted shots, pull-up vs catch-shoot",
        "label": "Shot Creation",
        "short": "CREATE",
        "group": "Shooting",
        "desc": "Unassisted %, Pull-up",
    },
    "drives": {
        "features": ["DRIVES", "DRIVE_FGA", "DRIVE_FG_PCT", "DRIVE_PTS", "DRIVE_AST", "DRIVE_TOV"],
        "default_weight": 1.0,
        "description": "Driving ability and efficiency",
        "label": "Drives",
        "short": "DRV",
        "group": "Shooting",
        "desc": "Drive volume + efficiency",
    },
    "playmaking": {
        "features": [
            "AST",
            "TOV",
            "ast_share",
            "tov_share",
            "e_ast_ratio",
            "e_tov_pct",
            "PASSES_MADE",
            "POTENTIAL_AST",
            "AST_PTS_CREATED",
        ],
        "default_weight": 1.0,
        "description": "Assists, passing, and turnovers",
        "label": "Playmaking",
        "short": "PLY",
        "group": "Playmaking",
        "desc": "AST, TOV, potential AST",
    },
    "rebounding": {
        "features": [
            "REB",
            "OREB",
            "DREB",
            "reb_share",
            "oreb_share",
            "dreb_share",
            "e_oreb_pct",
            "e_dreb_pct",
        ],
        "default_weight": 1.0,
        "description": "Rebounds",
        "label": "Rebounding",
        "short": "REB",
        "group": "Rebounding",
        "desc": "REB, OREB, DREB",
    },
    "defense": {
        "features": [
            "STL",
            "BLK",
            "stl_share",
            "blk_share",
            "contested_shots",
            "contested_shots_2pt",
            "contested_shots_3pt",
            "deflections",
            "charges_drawn",
            "def_loose_balls_recovered",
            "pct_box_outs_def",
        ],
        "default_weight": 1.0,
        "description": "Steals, blocks, contests, hustle",
        "label": "Defense",
        "short": "DEF",
        "group": "Defense",
        "desc": "STL, BLK, contests, deflections",
    },
    "usage": {
        "features": ["e_usg_pct"],
        "default_weight": 1.0,
        "description": "Usage rate",
        "label": "Usage",
        "short": "USG",
        "group": "Usage",
        "desc": "USG%",
    },
    "ball_handling": {
        "features": [
            "TOUCHES",
            "TIME_OF_POSS",
            "AVG_DRIB_PER_TOUCH",
            "FRONT_CT_TOUCHES",
            "ELBOW_TOUCHES",
            "POST_TOUCHES",
            "PAINT_TOUCHES",
        ],
        "default_weight": 1.0,
        "description": "Ball handling, touches, and possession time",
        "label": "Ball Handling",
        "short": "HAND",
        "group": "Playmaking",
        "desc": "Touches, time of poss",
    },
}

DIMENSIONS = [{"key": key, **value} for key, value in FEATURE_GROUPS.items()]
DEFAULT_WEIGHTS = {key: value["default_weight"] for key, value in FEATURE_GROUPS.items()}

STAT_CATEGORIES = [
    {
        "name": "Scoring Volume",
        "stats": [
            ("PTS", "PTS", False),
            ("FGA", "FGA", False),
            ("FTA", "FTA", False),
            ("3PA", "FG3A", False),
            ("MIN", "MIN", False),
            ("Pts Share", "pts_share", True),
            ("FGA Share", "fga_share", True),
        ],
    },
    {
        "name": "Efficiency",
        "stats": [
            ("TS%", "ts_pct", True),
            ("eFG%", "efg_pct", True),
            ("FG%", "fg_pct", True),
            ("3P%", "fg3_pct", True),
            ("FT%", "ft_pct", True),
        ],
    },
    {
        "name": "Shot Profile",
        "stats": [
            ("Rim %", "pct_fga_restricted", True),
            ("Paint %", "pct_fga_paint", True),
            ("Mid %", "pct_fga_midrange", True),
            ("Corner 3%", "pct_fga_corner3", True),
            ("Above 3%", "pct_fga_above_break3", True),
        ],
    },
    {
        "name": "Shot Creation",
        "stats": [
            ("Unast 2P%", "PCT_UAST_2PM", True),
            ("Unast 3P%", "PCT_UAST_3PM", True),
            ("Pull-up FGA", "PULL_UP_FGA", False),
            ("Pull-up FG%", "PULL_UP_FG_PCT", True),
            ("C&S FGA", "CATCH_SHOOT_FGA", False),
            ("C&S FG%", "CATCH_SHOOT_FG_PCT", True),
        ],
    },
    {
        "name": "Playmaking",
        "stats": [
            ("APG", "AST", False),
            ("TOV", "TOV", False),
            ("AST Share", "ast_share", True),
            ("Passes", "PASSES_MADE", False),
            ("Pot AST", "POTENTIAL_AST", False),
            ("AST Pts", "AST_PTS_CREATED", False),
        ],
    },
    {
        "name": "Defense",
        "stats": [
            ("STL", "STL", False),
            ("BLK", "BLK", False),
            ("Contests", "contested_shots", False),
            ("Deflections", "deflections", False),
            ("Charges", "charges_drawn", False),
            ("Loose Balls", "def_loose_balls_recovered", False),
        ],
    },
    {
        "name": "Physical",
        "stats": [("Height", "height_inches", False), ("Weight", "weight", False)],
    },
]
